### PR TITLE
Intercalate

### PR DESCRIPTION
**Pull request by pierroberto**
- Add `intercalate` function to `string` module.

### CODE REVIEW

**Review by davidecaruso — APPROVED** [review]
LGTM.

**Review by xzhavilla — COMMENTED** [review]
What about supporting an array of strings instead of just two arguments?

**Comment by pierroberto** [comment]
Currently, `fp-ts` supports an array of strings with its [intercalate](https://gcanti.github.io/fp-ts/modules/ReadonlyArray.ts.html#intercalate) function.

At the moment it seems not possible to define with a template literal a concatenation with an array of strings.

What about renaming `intercalate` function to `infix` and keep the support only for two strings?

**Comment by xzhavilla** [comment]
> At the moment it seems not possible to define with a template literal a concatenation with an array of strings.

It should be possible with recursive types. I managed to write the type, but apparently it's not working when applied to a function. We can play with it when you have time.

> What about renaming `intercalate` function to `infix` and keep the support only for two strings?

I support this solution, for the moment being.

**Review by xzhavilla — APPROVED** [review]

**Pull request merged**
